const languages = {
  "English" : [
    { 'value': '1', 'type': 'character', 'language_abbr':'en', 'keyCode':'48'},
    { 'value': '2', 'type': 'character', 'language_abbr':'en', 'keyCode':'49'},
    { 'value': '3', 'type': 'character', 'language_abbr':'en', 'keyCode':'50'},
    { 'value': '4', 'type': 'character', 'language_abbr':'en', 'keyCode':'51'},
    { 'value': '5', 'type': 'character', 'language_abbr':'en', 'keyCode':'52'},
    { 'value': '6', 'type': 'character', 'language_abbr':'en', 'keyCode':'53'},
    { 'value': '7', 'type': 'character', 'language_abbr':'en', 'keyCode':'54'},
    { 'value': '8', 'type': 'character', 'language_abbr':'en', 'keyCode':'55'},
    { 'value': '9', 'type': 'character', 'language_abbr':'en', 'keyCode':'56'},
    { 'value': '0', 'type': 'character', 'language_abbr':'en', 'keyCode':'57'},
    { 'value': 'a', 'type': 'character', 'language_abbr':'en', 'keyCode':'65'},
    { 'value': 'b', 'type': 'character', 'language_abbr':'en', 'keyCode':'66'},
    { 'value': 'c', 'type': 'character', 'language_abbr':'en', 'keyCode':'67'},
    { 'value': 'd', 'type': 'character', 'language_abbr':'en', 'keyCode':'68'},
    { 'value': 'e', 'type': 'character', 'language_abbr':'en', 'keyCode':'69'},
    { 'value': 'f', 'type': 'character', 'language_abbr':'en', 'keyCode':'70'},
    { 'value': 'g', 'type': 'character', 'language_abbr':'en', 'keyCode':'71'},
    { 'value': 'h', 'type': 'character', 'language_abbr':'en', 'keyCode':'72'},
    { 'value': 'i', 'type': 'character', 'language_abbr':'en', 'keyCode':'73'},
    { 'value': 'j', 'type': 'character', 'language_abbr':'en', 'keyCode':'74'},
    { 'value': 'k', 'type': 'character', 'language_abbr':'en', 'keyCode':'75'},
    { 'value': 'l', 'type': 'character', 'language_abbr':'en', 'keyCode':'76'},
    { 'value': 'm', 'type': 'character', 'language_abbr':'en', 'keyCode':'77'},
    { 'value': 'n', 'type': 'character', 'language_abbr':'en', 'keyCode':'78'},
    { 'value': 'o', 'type': 'character', 'language_abbr':'en', 'keyCode':'79'},
    { 'value': 'p', 'type': 'character', 'language_abbr':'en', 'keyCode':'80'},
    { 'value': 'q', 'type': 'character', 'language_abbr':'en', 'keyCode':'81'},
    { 'value': 'r', 'type': 'character', 'language_abbr':'en', 'keyCode':'82'},
    { 'value': 's', 'type': 'character', 'language_abbr':'en', 'keyCode':'83'},
    { 'value': 't', 'type': 'character', 'language_abbr':'en', 'keyCode':'84'},
    { 'value': 'u', 'type': 'character', 'language_abbr':'en', 'keyCode':'85'},
    { 'value': 'v', 'type': 'character', 'language_abbr':'en', 'keyCode':'86'},
    { 'value': 'w', 'type': 'character', 'language_abbr':'en', 'keyCode':'87'},
    { 'value': 'x', 'type': 'character', 'language_abbr':'en', 'keyCode':'88'},
    { 'value': 'y', 'type': 'character', 'language_abbr':'en', 'keyCode':'89'},
    { 'value': 'z', 'type': 'character', 'language_abbr':'en', 'keyCode':'90'}
    // { 'value': ' ', 'type': 'character', 'language_abbr':'en', 'keyCode':'32'},
    // { 'value': 'backspace', 'type': 'backspace', 'language_abbr':'en', 'keyCode':'8'},
    // { 'value': 'enter', 'type': 'enter', 'language_abbr':'en', 'keyCode':'186'}
  ],
  "Español" : [
    { 'value': '1', 'type': 'character', 'language_abbr':'es'},
    { 'value': '2', 'type': 'character', 'language_abbr':'es'},
    { 'value': '3', 'type': 'character', 'language_abbr':'es'},
    { 'value': '4', 'type': 'character', 'language_abbr':'es'},
    { 'value': '5', 'type': 'character', 'language_abbr':'es'},
    { 'value': '6', 'type': 'character', 'language_abbr':'es'},
    { 'value': '7', 'type': 'character', 'language_abbr':'es'},
    { 'value': '8', 'type': 'character', 'language_abbr':'es'},
    { 'value': '9', 'type': 'character', 'language_abbr':'es'},
    { 'value': '0', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'a', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'b', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'c', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'd', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'e', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'f', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'g', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'h', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'i', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'j', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'k', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'l', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'm', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'ñ', 'type': 'character', 'language_abbr':'es'},    
    { 'value': 'n', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'o', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'p', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'q', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'r', 'type': 'character', 'language_abbr':'es'},
    { 'value': 's', 'type': 'character', 'language_abbr':'es'},
    { 'value': 't', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'u', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'v', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'w', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'x', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'y', 'type': 'character', 'language_abbr':'es'},
    { 'value': 'z', 'type': 'character', 'language_abbr':'es'}
  ],
  "हिन्दी" : [
    { 'value': '०', 'type': 'character', 'language_abbr_abbr':'hi'},
    { 'value': '१', 'type': 'character', 'language_abbr':'hi'},
    { 'value': '२', 'type': 'character', 'language_abbr':'hi'},
    { 'value': '३', 'type': 'character', 'language_abbr':'hi'},
    { 'value': '४', 'type': 'character', 'language_abbr':'hi'},
    { 'value': '५', 'type': 'character', 'language_abbr':'hi'},
    { 'value': '६', 'type': 'character', 'language_abbr':'hi'},
    { 'value': '७', 'type': 'character', 'language_abbr':'hi'},
    { 'value': '८', 'type': 'character', 'language_abbr':'hi'},
    { 'value': '९', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'क', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ख', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ग', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'घ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ङ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'च', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'छ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ज', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'झ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ञ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ट', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ठ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ड', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ढ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ण', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'त', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'थ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'द', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ध', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'न', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'प', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'फ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ब', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'भ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'म', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'य', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'र', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ल', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'व', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'श', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ष', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'स', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ह', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ळ', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'क', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ष', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ज्', 'type': 'character', 'language_abbr':'hi'},
    { 'value': 'ञ', 'type': 'character', 'language_abbr':'hi'}
  ]
};
export default languages;